//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestWinForm.RightWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.TSUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.FirstModuleMenu[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.FirstModuleMenu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.SecondModuleMenu[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.SecondModuleMenu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.Controls[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestWinForm.RightWebService.Controls))]
    public partial class APIResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TSUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userPwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestWinForm.RightWebService.FirstModuleMenu[] FirstModuleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userCode {
            get {
                return this.userCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.userCodeField, value) != true)) {
                    this.userCodeField = value;
                    this.RaisePropertyChanged("userCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userPwd {
            get {
                return this.userPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.userPwdField, value) != true)) {
                    this.userPwdField = value;
                    this.RaisePropertyChanged("userPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string roleIds {
            get {
                return this.roleIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.roleIdsField, value) != true)) {
                    this.roleIdsField = value;
                    this.RaisePropertyChanged("roleIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string deptId {
            get {
                return this.deptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.deptIdField, value) != true)) {
                    this.deptIdField = value;
                    this.RaisePropertyChanged("deptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string post {
            get {
                return this.postField;
            }
            set {
                if ((object.ReferenceEquals(this.postField, value) != true)) {
                    this.postField = value;
                    this.RaisePropertyChanged("post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telephoneField, value) != true)) {
                    this.telephoneField = value;
                    this.RaisePropertyChanged("telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public WCFTestWinForm.RightWebService.FirstModuleMenu[] FirstModule {
            get {
                return this.FirstModuleField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstModuleField, value) != true)) {
                    this.FirstModuleField = value;
                    this.RaisePropertyChanged("FirstModule");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirstModuleMenu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FirstModuleMenu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestWinForm.RightWebService.SecondModuleMenu[] SendModuleMenuListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCFTestWinForm.RightWebService.SecondModuleMenu[] SendModuleMenuList {
            get {
                return this.SendModuleMenuListField;
            }
            set {
                if ((object.ReferenceEquals(this.SendModuleMenuListField, value) != true)) {
                    this.SendModuleMenuListField = value;
                    this.RaisePropertyChanged("SendModuleMenuList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModuleId {
            get {
                return this.ModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIdField, value) != true)) {
                    this.ModuleIdField = value;
                    this.RaisePropertyChanged("ModuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ModuleCode {
            get {
                return this.ModuleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleCodeField, value) != true)) {
                    this.ModuleCodeField = value;
                    this.RaisePropertyChanged("ModuleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecondModuleMenu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SecondModuleMenu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestWinForm.RightWebService.Controls[] ControlsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCFTestWinForm.RightWebService.Controls[] ControlsList {
            get {
                return this.ControlsListField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlsListField, value) != true)) {
                    this.ControlsListField = value;
                    this.RaisePropertyChanged("ControlsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ModuleId {
            get {
                return this.ModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleIdField, value) != true)) {
                    this.ModuleIdField = value;
                    this.RaisePropertyChanged("ModuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ModuleCode {
            get {
                return this.ModuleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleCodeField, value) != true)) {
                    this.ModuleCodeField = value;
                    this.RaisePropertyChanged("ModuleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Controls", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Controls : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ControlName {
            get {
                return this.ControlNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlNameField, value) != true)) {
                    this.ControlNameField = value;
                    this.RaisePropertyChanged("ControlName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ControlId {
            get {
                return this.ControlIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlIdField, value) != true)) {
                    this.ControlIdField = value;
                    this.RaisePropertyChanged("ControlId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ControlCode {
            get {
                return this.ControlCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlCodeField, value) != true)) {
                    this.ControlCodeField = value;
                    this.RaisePropertyChanged("ControlCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RightWebService.RightWebServiceSoap")]
    public interface RightWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strUserCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginUserInfo", ReplyAction="*")]
        WCFTestWinForm.RightWebService.GetLoginUserInfoResponse GetLoginUserInfo(WCFTestWinForm.RightWebService.GetLoginUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WCFTestWinForm.RightWebService.GetLoginUserInfoResponse> GetLoginUserInfoAsync(WCFTestWinForm.RightWebService.GetLoginUserInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public WCFTestWinForm.RightWebService.GetLoginUserInfoRequestBody Body;
        
        public GetLoginUserInfoRequest() {
        }
        
        public GetLoginUserInfoRequest(WCFTestWinForm.RightWebService.GetLoginUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassward;
        
        public GetLoginUserInfoRequestBody() {
        }
        
        public GetLoginUserInfoRequestBody(string strUserCode, string strPassward) {
            this.strUserCode = strUserCode;
            this.strPassward = strPassward;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCFTestWinForm.RightWebService.GetLoginUserInfoResponseBody Body;
        
        public GetLoginUserInfoResponse() {
        }
        
        public GetLoginUserInfoResponse(WCFTestWinForm.RightWebService.GetLoginUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCFTestWinForm.RightWebService.APIResult GetLoginUserInfoResult;
        
        public GetLoginUserInfoResponseBody() {
        }
        
        public GetLoginUserInfoResponseBody(WCFTestWinForm.RightWebService.APIResult GetLoginUserInfoResult) {
            this.GetLoginUserInfoResult = GetLoginUserInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RightWebServiceSoapChannel : WCFTestWinForm.RightWebService.RightWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RightWebServiceSoapClient : System.ServiceModel.ClientBase<WCFTestWinForm.RightWebService.RightWebServiceSoap>, WCFTestWinForm.RightWebService.RightWebServiceSoap {
        
        public RightWebServiceSoapClient() {
        }
        
        public RightWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RightWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RightWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RightWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestWinForm.RightWebService.GetLoginUserInfoResponse WCFTestWinForm.RightWebService.RightWebServiceSoap.GetLoginUserInfo(WCFTestWinForm.RightWebService.GetLoginUserInfoRequest request) {
            return base.Channel.GetLoginUserInfo(request);
        }
        
        public WCFTestWinForm.RightWebService.APIResult GetLoginUserInfo(string strUserCode, string strPassward) {
            WCFTestWinForm.RightWebService.GetLoginUserInfoRequest inValue = new WCFTestWinForm.RightWebService.GetLoginUserInfoRequest();
            inValue.Body = new WCFTestWinForm.RightWebService.GetLoginUserInfoRequestBody();
            inValue.Body.strUserCode = strUserCode;
            inValue.Body.strPassward = strPassward;
            WCFTestWinForm.RightWebService.GetLoginUserInfoResponse retVal = ((WCFTestWinForm.RightWebService.RightWebServiceSoap)(this)).GetLoginUserInfo(inValue);
            return retVal.Body.GetLoginUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFTestWinForm.RightWebService.GetLoginUserInfoResponse> WCFTestWinForm.RightWebService.RightWebServiceSoap.GetLoginUserInfoAsync(WCFTestWinForm.RightWebService.GetLoginUserInfoRequest request) {
            return base.Channel.GetLoginUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFTestWinForm.RightWebService.GetLoginUserInfoResponse> GetLoginUserInfoAsync(string strUserCode, string strPassward) {
            WCFTestWinForm.RightWebService.GetLoginUserInfoRequest inValue = new WCFTestWinForm.RightWebService.GetLoginUserInfoRequest();
            inValue.Body = new WCFTestWinForm.RightWebService.GetLoginUserInfoRequestBody();
            inValue.Body.strUserCode = strUserCode;
            inValue.Body.strPassward = strPassward;
            return ((WCFTestWinForm.RightWebService.RightWebServiceSoap)(this)).GetLoginUserInfoAsync(inValue);
        }
    }
}
